Koboshecom/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = []

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    # Media URLs
    path('media/<path:path>', serve, {'document_root': settings.MEDIA_ROOT}),
    
    # Admin URLs
    path('admin/', admin.site.urls),
    
    # Cart URLs
    path('cart/', include('cart.urls', namespace='cart')),
    
    # Authentication URLs
    path('members/', include('django.contrib.auth.urls')),
    
    # Members URLs
    path('members/', include('members.urls', namespace='members')),
    
    # Kobosh URLs
    path('', include('kobosh.urls', namespace='kobosh')),
    
    # Static URLs
    path('static/<path:path>', serve, {'document_root': settings.STATIC_ROOT}),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove,
         name='cart_remove'),
    

]

kobosh/urls.py
from django.urls import path
from . import views

app_name = "kobosh"

urlpatterns = [
    path('payment/', views.payment, name='payment'),
    path('thebasement/', views.home, name='thebasement'),
    path('', views.home, name='home'),
    path('categories/', views.home, name='cate'),
    path('search/', views.search, name='search'),
    path('<slug:category_slug>/', views.home, 
        name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail,
        name = 'product_detail'),
]

cart/models.py
from django.db import models


# Create your models here.
from django import forms
PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]
class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
                                choices=PRODUCT_QUANTITY_CHOICES,
                                coerce=int)
    override = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

cart/forms.py
from django import forms
PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int)
    override = forms.BooleanField(required=False,
                                  initial=False,
                                  widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from kobosh.models import Category, Product
from .cart import Cart
from .forms import CartAddProductForm
from django.contrib.auth.models import User

def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if User is None:
        return redirect("members:login")
    else:
        if form.is_valid():
            cd = form.cleaned_data
            cart.add(product=product, quantity=cd['quantity'], override_quantity=cd['override'])
            
    return redirect('cart:cart_detail')   

def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request,category_slug=None):
    category = None
    categories = Category.objects.all()

    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category,
                                     slug=category_slug)
        products = products.filter(category=category)
    
    cart = Cart(request)


    context = {
      'cart': cart,
      'category' : category,
      'categories': categories,
      'products': products
      }
    return render(request, 'cart/cart.html', context)

cart/templates/cart/cart.html
{% extends 'kobosh/base.html' %}

{% load static %}
{% load humanize %}
{% block 'content' %}

<head>
	<link rel="stylesheet" href="{% static 'kobosh/cart.css'%}">
	<style>
		.fa-cart-shopping {
			color: #000000;
		}
		@media screen and (max-width:767px) {
			nav #search {
        display: block;
        position: relative;
        left: -140%;
        top: -7px;
        z-index: 1;
        font-size: 20px;
        color: white;
    }
    #profile {
        position: relative;
        left: -2pc;
        top: -31px;
    }

    #cart {
        position: relative;
        left: .8pc;
        top: -58px;
        width: 91%;
    }
	.newsletter input[type='email'] {
        height: 46px;
        border: none;
        width: 65.4%;
        position: relative;
        top: 20px;
        left: .5%;
        font-weight: bold;
        color: black;
        padding-left: 50px;
        border-radius: 50px 0px 0px 50px;
    }

		}
@media only screen and (min-width: 768px) and (max-width: 1023px) {
	nav #search {
        position: relative;
        left: -6pc;
        top: -7px;
        font-size: 15px;
        z-index: 2;
		font-size: 20px;
        color: white;
    }

    nav #profile {
        position: relative;
        left: .8pc;
        top: -31px;
    }

    nav #cart {
        position: relative;
        left: -3pc;
        top: -58px;
        width: 91%;
    }
	.newsletter input[type='email'] {
  height: 46px;
  border: none;
  width: 47.6%;
  position: relative;
  top: 19px;
  left: .5%;
  font-weight: bold;
  color: black;
  padding-left: 50px;
  border-radius: 50px 0px 0px 50px;
}
nav input {
        display: none;
        border-radius: 20px;
        border: none;
        padding: 10px;
        /* padding-left: 35px; */
        float: right;
        color: black;
        position: relative;
        /* right: 9%; */
        margin-top: 1.3pc;
        font-size: 12px;
        width: 18%;
        height: 33px;
    }
}

	@media only screen and (min-width: 1024px) {

		footer .foot_head .newsletter input[type='email'] {
        height: 46px;
        border: none;
        width: 40%;
        position: relative;
        top: 21px;
        left: -68px;
        font-weight: bold;
        color: black;
        padding-left: 50px;
        border-radius: 50px;
        border-radius: 50px 0px 0px 50px;
    }
	}
	</style>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<div class="center-wrapper">
	<div class="content">
		<form action="{% url 'kobosh:payment' %}" id="myForm">
            {% for item in cart %}
                {% with product=item.product %}
                    <div class="bag-product">
                        <div class="image">
                            <img onclick="location.href='{{ product.get_absolute_url }}'" src="{% if product.image %}{{ product.image }}{% else %}{% static "img/no_image.png" %}{% endif %}" class="product-image">
                        </div>
                        <div class="description">
                            <h1>{{ product.name }}</h1>
                            <p class="description-text">{{ product.description }}</p>
                            <h2>&#8358; {{ item.new_price|intcomma }}</h2>
                            <div class="quantity-wrapper">
                                <div>
                                    <label for="quantity" style="margin-right: 0.5rem;">Quantity: {{ item.quantity }}</label>
                                </div>
                                <button type="button" class="btn-remove" data-product-id="{{ product.id }}">Remove</button>
                            </div>
                        </div>
                    </div>
                {% endwith %}
            {% endfor %}
                

<div class="bag-total">
    <div class="subtotal">
        <p class="small">Subtotal:</p>
        <p class="small">NGN {{ cart.get_total_price }}</p>
    </div>
    <div class="delivery">
        <p class="small">Delivery (Standard - 2 working days):<br>
            <span class="change-delivery">Change delivery method</span>
        </p>
        <p class="small">Free</p>
    </div>
    <div class="total">
        <h3>Total:</h3>
        <h3>NGN {{ cart.get_total_price }}</h3>
    </div>

                <button type="submit" class="btn-go-checkout">
                    <i class="fas fa-lock"></i>
                    <span>Go to Checkout</span>
                </button>
        </form>
        
        <!-- Separate form for item removal -->
        <form id="removeForm" method="post" style="display: none;">
            {% csrf_token %}
        </form>
        

	</div>
</div>
<div class="bg"></div>


<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function() {
        $(".btn-remove").on("click", function() {
            var productId = $(this).data("product-id");
            $("#removeForm").attr("action", "{% url 'cart:cart_remove' 0 %}".replace("0", productId));
            $("#removeForm").submit();
        });
    });
</script>

<script>

	function submitForm() {
		document.getElementById("myForm").submit();
	}
</script>

{% endblock %}