Koboshecom/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = []

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    # Media URLs
    path('media/<path:path>', serve, {'document_root': settings.MEDIA_ROOT}),
    
    # Admin URLs
    path('admin/', admin.site.urls),
    
    # Cart URLs
    path('cart/', include('cart.urls', namespace='cart')),
    
    # Authentication URLs
    path('members/', include('django.contrib.auth.urls')),
    
    # Members URLs
    path('members/', include('members.urls', namespace='members')),
    
    # Kobosh URLs
    path('', include('kobosh.urls', namespace='kobosh')),
    
    # Static URLs
    path('static/<path:path>', serve, {'document_root': settings.STATIC_ROOT}),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove,
         name='cart_remove'),
    

]

members/urls.py
from django.urls import path
from . import views

app_name = 'members'

urlpatterns = [
    path('login_user/', views.login_user, name='login_user'),
    path('signup_user/', views.signup_user, name='signup_user'),
    path('forgotpass/', views.forgotpass, name='forgotpass'),
]

members/models.py
from django.db import models

# Create your models here.

members/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.contrib import messages
from django.contrib.auth.password_validation import validate_password
from kobosh.models import Category, Product 
from django.shortcuts import render, get_object_or_404

def login_user(request,category_slug=None):
    category = None
    categories = Category.objects.all()

    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category,
                                     slug=category_slug)
        products = products.filter(category=category)
    
    
    if request.method == 'POST':
        email = request.POST.get("email")
        password = request.POST.get("password")
        user = authenticate(request, email=email, password=password)
        if user is not None:
            login(request, user)

 

            return redirect('kobosh:home')
        else:
            messages.error(request, "There was an error logging in. Please try again.")
            return redirect('members:login_user')

    context = {
        'category' : category,
        'categories': categories,
        'products': products
        }
    
   
    return render(request, 'members/login.html', context)


def signup_user(request,category_slug=None):
    category = None
    categories = Category.objects.all()

    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category,
                                     slug=category_slug)
        products = products.filter(category=category)
    
    if request.method == 'POST':
        email = request.POST.get("email")
        password = request.POST.get("pass")
        password1 = request.POST.get("cpass")
        username = request.POST.get("full_name")

        # Check if passwords match
        if password != password1:
            messages.error(request, "Passwords do not match. Please try again.")
            return redirect('members:signup_user')

        # Validate password
        try:
            validate_password(password)
        except Exception as e:
            messages.error(request, str(e))
            return redirect('members:signup_user')

        # Check if email already exists
        if User.objects.filter(email=email).exists():
            messages.error(request, "Email already exists. Please use a different email.")
            return redirect('members:signup_user')

        # Create the user
        user = User.objects.create_user(email=email, password=password, username=username)
        user.save()

        return redirect('kobosh:home')

    
    context = {
        'category' : category,
        'categories': categories,
        'products': products
        }


    return render(request, 'members/signup.html', context)

def forgotpass(request,category_slug=None):
    category = None
    categories = Category.objects.all()

    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category,
                                     slug=category_slug)
        products = products.filter(category=category)
    

    
    context = {
        'category' : category,
        'categories': categories,
        'products': products
        }
    return render(request, 'members/forgotpass.html', context)

members/templates/members/forgotpass.html
{% extends 'kobosh/base.html' %}

{% load static %}
{% block 'content' %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'kobosh/login&signup.css' %}">
    <style>
        .fa-user {
            color: #000000;
        }
    </style>
</head>

<body>
    <div class="all_forms">
        <div class="reset create">
            <form action="" method="post">
                {% csrf_token %}
                <h2>Forgot Password</h2>
                <label for="input">
                    <strong>Reset email</strong>
                    <br>
                    <input id="full_name" type="email">
                </label><br><br>
                <input type="submit" value="Send reset mail" style="width: 96%;" class="account_create">
    
            </form>
        </div>
    </div>
</body>

</html>
{% endblock %}

members/templates/members/login.html
{% extends 'kobosh/base.html' %}
{% block 'content' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'kobosh/login&signup.css' %}">
    <style>
        .fa-user {
            color: #000000;
        }
        @media screen and (max-width:767px) {
            .bottom {
                position: relative;
                left: 2pc;
            }
            input {
                position: relative;
                left: -6px;
            }
        }
    </style>
</head>

<body>
   
    <div class="all_forms">
        <div class="create" style="top: 8pc;">
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                    {% endfor %}
            </ul>
            {% endif %}
            <form action="" method="post" style="left: 9px; position: relative;">
                {% csrf_token %}

                <h2>Login</h2>
                <hr style="position: relative; left:-12px" ; id="h2_id">
                <label for="input">
                    <strong>Email Address or Phone number</strong>
                    <br>
                    <input id="full_name" type="email" name="email">
                </label><br><br>
                <label for="input">
                    <strong>Password</strong>
                    <a style="text-decoration: none;" id="forgotpass" href="{% url 'members:forgotpass' %}">Forgot password?</a>
                    <br>
                    <input id="full_name" type="password" name="password">
                </label><br><br>
                <input style="width: 95.4%;" type="submit" value="Login" class="account_create" name="passowrd">

            </form>
            <div class="bottom" style="left: 9px; position: relative;">
                <p style="color: black;">Don't have an account?</p>
                <input onclick="location.href='{% url 'members:signup_user' %}'" id="create_acc" type="submit"
                    value="Create an Account">
            </div>
        </div>
    </div>
</body>

</html>
{% endblock %}

members/templates/members/signup.html
{% extends 'kobosh/base.html' %}
{% load static %}
{% block 'content' %}
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'kobosh/login&signup.css' %}">
    <style>
        .fa-user {
            color: #000000;
        }
        @media screen and (max-width:767px) {
            input, label strong {
                position: relative;
                left: -15px;
            }
            input[type='submit']{
                position: relative;
                left: -12px;
            }
            .create h2, .create hr {
                width: 92%;
            }
        }
    </style>
</head>

<body>
   
    <div class="all_forms">
        <div class="create">
            <form action="" method="post" style="left: 8px; position: relative;">
                {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
                {% csrf_token %}
                <h2>Create An Account</h2>
                <hr style="left: -9px; position: relative;" id="h2_id">
                <label for="input">
                    <strong>Full name</strong>
                    <br />
                    <input id="full_name" type="text" name="full_name" /> </label><br /><br />
                    <label for="input">
                        <strong>Phone Number</strong>
                        <br />
                        <input id="full_name" type="number" /> </label><br /><br />
                <label for="input">
                    <strong>Email</strong>
                    <br />
                    <input id="full_name" type="email" name="email" /> </label><br /><br />
                <label for="input">
                    <strong>Password</strong>
                    <br />
                    <input id="full_name" type="password" name="pass" /> </label><br /><br />
                <label for="input">
                    <strong>Confirm Password</strong>
                    <br />
                    <input id="full_name" type="password" name="cpass" /> </label><br />
                <br />
                <br />
    
                <input style="width: 95.4%;" type="submit" value="Create account" class="account_create" />
            </form>
            <div class="bottom">
                <p>By signing up you accept our <a href="#">terms and conditions</a> & <a href="#">privacy policy</a></p>
    
                <p>Already have an Account?</p>
                <input onclick="location.href='{% url 'members:login_user' %}'" style="left: 8px; position: relative;" id="create_acc" type="submit" value="Login">
    
                </div>
        </div>
    </div>
</body>

</html>
{% endblock %}