Koboshecom/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = []

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    # Media URLs
    path('media/<path:path>', serve, {'document_root': settings.MEDIA_ROOT}),
    
    # Admin URLs
    path('admin/', admin.site.urls),
    
    # Cart URLs
    path('cart/', include('cart.urls', namespace='cart')),
    
    # Authentication URLs
    path('members/', include('django.contrib.auth.urls')),
    
    # Members URLs
    path('members/', include('members.urls', namespace='members')),
    
    # Kobosh URLs
    path('', include('kobosh.urls', namespace='kobosh')),
    
    # Static URLs
    path('static/<path:path>', serve, {'document_root': settings.STATIC_ROOT}),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove,
         name='cart_remove'),
    

]

kobosh/urls.py
from django.urls import path
from . import views

app_name = "kobosh"

urlpatterns = [
    path('payment/', views.payment, name='payment'),
    path('thebasement/', views.home, name='thebasement'),
    path('', views.home, name='home'),
    path('categories/', views.home, name='cate'),
    path('search/', views.search, name='search'),
    path('<slug:category_slug>/', views.home, 
        name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail,
        name = 'product_detail'),
]

members/urls.py
from django.urls import path
from . import views

app_name = 'members'

urlpatterns = [
    path('login_user/', views.login_user, name='login_user'),
    path('signup_user/', views.signup_user, name='signup_user'),
    path('forgotpass/', views.forgotpass, name='forgotpass'),
]

kobosh/models.py
from django.db import models
from django.urls import reverse
# Create your models here.


from PIL import Image
from io import BytesIO
from django.core.files.uploadedfile import InMemoryUploadedFile

from django.core.exceptions import ValidationError

from decimal import Decimal

from django.contrib.humanize.templatetags.humanize import intcomma

class CommaSeparatedIntegerField(models.DecimalField):
    def formated_price(self):
        return "{:,.2f}".format(self.new_price)

class Category(models.Model):

    name = models.CharField(max_length=200)

    image = models.URLField(max_length=200)

    slug = models.SlugField(max_length=200,
                            unique=True)

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=["name"]),
        ]
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('kobosh:product_list_by_category',
                       args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category,
                                 related_name='products',
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    image = models.URLField(max_length=200)

    image1 = models.URLField(max_length=200)

    image2 = models.URLField(max_length=200)
                              
    description = models.TextField(blank=True, max_length=250)
    old_price = CommaSeparatedIntegerField(max_digits=10, decimal_places=0, null=True)
    new_price = models.DecimalField(max_digits=10, decimal_places=0, null=True)
    def formatted_price(self):
        return intcomma(self.new_price)
    
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)

    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['id', 'slug']),
            models.Index(fields=['name']),
            models.Index(fields=['-created']),
        ]

    def __str__(self):
        return self.name
        
    def get_absolute_url(self):
        return reverse('kobosh:product_detail',
            args=[self.id, self.slug])

kobosh/forms.py
from django import forms 

class SearchForm(forms.Form):
    query = forms.CharField(max_length=100, required=False)

kobosh/views.py
from . models import Category, Product 
from django.shortcuts import render

from cart.forms import CartAddProductForm

from django.shortcuts import render, get_object_or_404
from django.shortcuts import render, HttpResponse, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login, logout
from django.contrib.auth.decorators import login_required


import re
from bs4 import BeautifulSoup
from django.db.models import Q


def home(request,category_slug=None):
    category = None
    categories = Category.objects.all()

    products = Product.objects.filter(available=True)
    # new_price = Product.formatted_price
    if category_slug:
        category = get_object_or_404(Category,
                                     slug=category_slug)
        products = products.filter(category=category)
    
    context = {
        'category' : category,
        'categories': categories,
        'products': products,
        # 'new_price': new_price,
        }
    
    if request.resolver_match.url_name == 'home':
        template_name = 'kobosh/home.html'
    else:
        template_name = 'kobosh/categories.html'
    return render(request, template_name, context)


def product_detail(request, id, slug,category_slug=None):
    category = None
    categories = Category.objects.all()

    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category,
                                     slug=category_slug)
        products = products.filter(category=category)
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()

    products = Product.objects.filter(available=True)


    context = {
        'product' : product,
        'products': products,
        'cart_product_form': cart_product_form,
        'category' : category,
        'categories': categories,
        }
    
    

    return render(request, 'kobosh/details.html', context)


def payment(request,category_slug=None):
    category = None
    categories = Category.objects.all()

    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category,
                                     slug=category_slug)
        products = products.filter(category=category)
    
    context = {
        'category' : category,
        'categories': categories,
        'products': products
        }
    
    return render(request, 'kobosh/payments.html', context)



def search(request,category_slug=None):
    category = None
    categories = Category.objects.all()

    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category,
                                     slug=category_slug)
        products = products.filter(category=category)
    
  
    if request.method == 'GET':
        query = request.GET.get('query')

        # Search the database for products matching the query
        result = Product.objects.filter(Q(name__icontains=query) | Q(new_price__icontains=query))
        print(result)
        context = {
        'category' : category,
        'categories': categories,
        'results': result,
        }
        return render(request, 'kobosh/result.html',context)

kobosh/templates/kobosh/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Bokosh</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
  <link rel="shortcut icon" href="{% static 'kobosh/hero_image.png' %}" type="image/x-icon">
  <link rel="stylesheet" href="{% static 'kobosh/style.css' %}">
</head>

<body>
  <nav>
    
    <div class="burger">
      <i class="fa-solid fa-bars"></i>

      
    </div>

    <div class="logo" id="nav-logo">
      <h2 onclick='location.href="{% url 'kobosh:home' %}"' | escapejs style="cursor: pointer;">BOKOSH</h2>
    </div>

    <ul>
      <li class="_home" onclick='location.href="{% url 'kobosh:home' %}"' | escapejs>HOME</li>
      <div class="all_li">
        <!-- onclick='location.href="{% url 'kobosh:cate' %}"' -->
        <li id="dt" class="onhover"   | escapejs>CATEGORIES <i class="fa-solid fa-chevron-down"></i></li> 

      <div name="" id="mySelect" >
        {% for c in categories %}
        <div id="list" onclick='location.href="{{ c.get_absolute_url }}"' | escapejs>{{ c.name }}</div>
        {% endfor %}
      </div>
      </div>

      <li id="pays" onclick='location.href="{% url 'kobosh:payment' %}"' | escapejs>PAYMENTS</li>

    </ul>
    <form id="search-form" action="{% url 'kobosh:search' %}" method="get">
      <input type="search" name="query" id="search-input" placeholder="Search Products" />
    </form>
    <div class="icons">
      <i class="fa-solid fa-magnifying-glass" id="search"></i>
      <i onclick='location.href="{% url 'members:login_user' %}"' | escapejs id="profile" class="fa-solid fa-user"></i>
      <i onclick='location.href="{% url 'cart:cart_detail' %}"' | escapejs id="cart"
        class="fa-solid fa-cart-shopping"></i>
    </div>
  </nav>




  {% block 'content' %}



  {% endblock %}


  <footer>
    <div class="foot_head">
      <div class="logo">
        <h2>BOKOSH</h2>
      </div>
      <div class="newsletter">
        <h3>We love to keep you updated with our new offers</h3>
        <h2>Subscribe to our newsletter now!</h2>
        <form action="" id="form">
          <i class="fa-solid fa-envelope" id="new_mail"></i>
          <input id="sub" type="email" placeholder="Enter Your Email" />
          <input id="subtle" type="submit" value="SUBSCRIBE NOW" />
        </form>
      </div>
    </div>
    <div class="foot_bottom">
      <div class="bt_left">
        <h3>CATEGORIES LINKS</h3>
        <hr>
        <ul>
          <li><a href=".">Men Collection</a></li>
          <li><a href=".">Women Collection</a></li>
          <li><a href=".">Kids Collection</a></li>
          <li><a href=".">Fashion Accessories</a></li>
          <li><a href=".">Other Categories</a></li>
        </ul>

        <ul class="right">
          <li><a href=".">Phones & Gadgets</a></li>
          <li><a href=".">Laptops & Accessories</a></li>
          <li><a href=".">TV & Electronics</a></li>
          <li><a href=".">Home Appliances</a></li>
          <li><a href=".">Furniture & Beddings</a></li>
        </ul>
      </div>
      <div class="bt_middle">
        <h3>OTHER LINKS</h3>
        <hr />
        <ul>
          <li><a href=".">Home</a></li>
          <li><a href=".">About Us</a></li>
          <li><a href=".">Shop</a></li>
          <li><a href=".">Account</a></li>
          <li><a href=".">Terms & Conditions</a></li>
        </ul>
      </div>
      <div class="bt_right">
        <h3>HOW CAN BOKOSH HELP YOU</h3>
        <hr />
        <ul>
          <li><a href=".">Delivery Anywhere in Nigeria</a></li>
          <li><a href=".">Shopping Online</a></li>
          <li><a href=".">Return & Refund Policy</a></li>
          <li><a href=".">Report a Problem</a></li>
          <li><a href=".">Our Offices & Warehouse</a></li>
        </ul>
      </div>
    </div>
  </footer>
  <hr id="last_hr" />
  <div class="payment">
    <h3>PAYMENTS METHODS</h3>
    <h2>CONNECT WITH US</h2>
    <div class="socials">
      <i class="fa-brands fa-twitter"></i>
      <i class="fa-brands fa-facebook"></i>
      <i class="fa-brands fa-instagram"></i>
    </div>
    <!-- <img src="" alt="">
          <img src="" alt="">
          <img src="" alt=""> -->
  </div>
  <div class="copyright">
    <p>Copyright &copy; Bokosh 2023</p>

    <i onclick="location.href='.'" class="fa-solid fa-arrow-up" id="arrow"></i>
  </div>


<script>
  const select = document.getElementById('mySelect');
  const butdrop = document.querySelector('.fa-chevron-down');
  const cate = document.querySelector('.onhover');
  cate.addEventListener('click', ()=> {
    select.classList.toggle('dropdown');
    butdrop.classList.toggle("show")
  })
</script>
  

  <script>
    let selectElement = document.getElementById('mySelect');
    selectElement.addEventListener('change', function() {
      const selectedValue = this.value;
      if (selectedValue !== '') {
        window.location.href = selectedValue;
      }
    });
  </script>


  <script src="https://kit.fontawesome.com/9da17deac8.js" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.js"></script>
  <script src="{% static 'kobosh/scripts.js' %}"></script>
  <script>

      var body = document.getElementsByTagName('body')[0];
      var elementToShow = document.querySelector("nav input");
      var icons = document.querySelector(".icons");
      var button = document.getElementById("search");
      var profile = document.getElementById("profile");
      var cart = document.getElementById("cart");
      const mediaPhone = window.matchMedia('(max-width: 768px)')
      const mediaTab = window.matchMedia('(min-width: 768px) and (max-width: 1023px)');
      // body.addEventListener("click", function () {
      //   if (elementToShow.style.display !== "none") {
      //     elementToShow.style.display = "none";
      //   }
      // });


      if (mediaPhone.matches) {
        body.addEventListener("click", function (event) {
            if (!elementToShow.contains(event.target)) {
              elementToShow.style.display = "none";
              cart.style.display = "block";
              button.style.display = "block";
              button.style.left = "-75px";
              profile.style.display = "block";
              icons.style.left = '-27px';
            }
});

button.addEventListener("click", function(event) {
        event.stopPropagation();
        elementToShow.style.display = "block";
        cart.style.display = "none";
        profile.style.display = "none";
        button.style.display = "none";
        elementToShow.style.top = '.9pc'
        elementToShow.style.left = '15pc'
      });
      }
      if (mediaTab.matches) {
  
        body.addEventListener("click", function (event) {
            if (!elementToShow.contains(event.target)) {
              elementToShow.style.display = "none";
              cart.style.display = "block";
              button.style.left = "-96px";
              button.style.display = "block";
              profile.style.display = "block";
              icons.style.left = '-73px'
            }
});

button.addEventListener("click", function(event) {
        event.stopPropagation();
        elementToShow.style.display = "block";
        cart.style.display = "none";
        profile.style.display = "none";
        button.style.display = "none";
        elementToShow.style.top = '-2.4pc'
        elementToShow.style.left = '-4pc'
      });
} 
  </script>
  <script>
    document.addEventListener("DOMContentLoaded", function () {
      var input = document.getElementById("search-input");
      var resultsContainer = document.getElementById("search-results");

      input.addEventListener("input", function () {
        var query = input.value;

        if (query.trim().length > 0) {
          fetch("/search/?query=" + encodeURIComponent(query))
            .then(function (response) {
              return response.json();
            })
            .then(function (data) {
              displayResults(data);
            });
        } else {
          resultsContainer.innerHTML = "";
        }
      });

      function displayResults(results) {
        var html = "";

        results.forEach(function (result) {
          html += "<div>" + result.title + "</div>";  // Customize based on your model

          // Append additional data or customize the result display as needed
        });

        resultsContainer.innerHTML = html;
      }
    });
  </script>

<script>
  const hamburgerMenu = document.querySelector('.hamburger-menu');
var body = document.querySelector('body');






btn = document.querySelector(".burger");

navlist = document.querySelector("ul");

bod = document.querySelector("#head");

btn1 = document.querySelector(".burger1");


btn.addEventListener("click", (event) => {
  btn.innerHTML = btn.innerHTML.includes("fa-xmark")
    ? `<i class="fa-solid fa-bars"></i>`
    : `<i class="fa-sharp fa-solid fa-xmark"></i>`;
      navlist.classList.toggle("clipped").checked;
      event.stopPropagation();

});

// body.addEventListener("click", (event) => {
//       event.stopPropagation();

//     navlist.classList.toggle("clipped").checked = false;
// });

</script>

</body>

</html>

kobosh/templates/kobosh/categories.html
{% extends 'kobosh/base.html' %}

{% block 'content' %}
{% load humanize %}

{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="stylesheet" href="{% static 'kobosh/cate.css' %}">
  <title>Category</title>
  <link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.css"
/>
<link rel="stylesheet" href="{% static 'kobosh/modern.css' %}">
<script src="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.js"></script>
<style>
  nav ul .onhover{
      color: #000000;
      font-size:18px;
    }
    
</style>
</head>


<body>




  <div class="all_page">
    <div class="left_side">

      
      <div id="">
        <ul class="links">
          <h1>Categories</h1>
          <hr />
          <a href="{% url 'kobosh:cate' %}">All</a>
          {% for c in categories %}
          {% if slug == 'c.slug' %}
          <a id="active" href="{{ c.get_absolute_url }}">{{ c.name }}</a>
          {% endif %}
          
          <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
          
          {% endfor %}
        </ul>
      </div>
    </div>
    
    <div class="all">
      {% for product in products %}
      <div class="prod swiper">
        <div class="swiper-wrapper" onclick="location.href='{{ product.get_absolute_url }}'">
          <div class="swiper-slide">
            <img src="{% if product.image %}{{ product.image }}{% else %}{% 
              static "img/no_image.png" %}{% endif %}" alt="">
          </div>
          <div class="swiper-slide">
            <img src="{% if product.image1 %}{{ product.image1 }}{% else %}{% 
              static "img/no_image.png" %}{% endif %}" alt="">
          </div>
          <div class="swiper-slide">
            <img src="{% if product.image2 %}{{ product.image2 }}{% else %}{% 
              static "img/no_image.png" %}{% endif %}" alt="">
          </div>
        </div>
        <div class="swiper-pagination down"></div>
        
        <h3>{{ product.name }}</h3>
        <p><strong class="price"> &#8358; {{ product.new_price|intcomma }}</strong></p>

        <p id="old_pric"><del><sub style="color: black;">&#8358; {{ product.old_price }}</sub></del></p>

        <button onclick="location.href='{{ product.get_absolute_url }}'">Add to Cart</button>
      </div>
      {% endfor %}
    </div>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.js"></script>
  <script src="{% static 'kobosh/swiper.js' %}"></script>

  <script>
    const hamburgerMenu = document.querySelector('.hamburger-menu');
  var body = document.querySelector('body');
  
  
  
  
  
  
  btn = document.querySelector(".burger");
  
  navlist = document.querySelector("ul");
  
  bod = document.querySelector("#head");
  
  btn1 = document.querySelector(".burger1");
  
  
  btn.addEventListener("click", (event) => {
    btn.innerHTML = btn.innerHTML.includes("fa-xmark")
      ? `<i class="fa-solid fa-bars"></i>`
      : `<i class="fa-sharp fa-solid fa-xmark"></i>`;
        navlist.classList.toggle("clipped").checked;
        event.stopPropagation();
  
  });
  
  // body.addEventListener("click", (event) => {
  //       event.stopPropagation();
  
  //     navlist.classList.toggle("clipped").checked = false;
  // });
  
  </script>
  

  <script src="https://kit.fontawesome.com/9da17deac8.js" crossorigin="anonymous"></script>


</body>

</html>
{% endblock %}

kobosh/templates/kobosh/details.html
{% extends "kobosh/base.html" %}
{% load humanize %}
{% load static %}
{% block title %}
{{ product.name }}
{% endblock %}
{% block 'content' %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'kobosh/style.css' %}">
    <link rel="stylesheet" href="{% static 'kobosh/modern.css' %}">
    <title>Details</title>
    <style>

        @media screen and (min-device-width: 0) and (max-device-width: 767px) {
            .right_des {
                position: relative;
                width: 50%;
                top: -14pc;
                float: right;
            }
            .right_des h2,
            .right_des p,
            .des,
            select,
            option {
                color: black;
            }
            .items {
                width: 81%;
                position: relative;
                top: 5pc;
                border: 1px solid black;
                padding: 15px;
                left: 5%;
                font-size: 12px;
                padding-bottom: 50px;
                border-radius: 25px;
                margin-bottom: 320px;
            }

            .items_img {
                width: 47%;
                height: 230px;
            }

            .items .des {
                position: relative;
                top: 8pc;
                width: 200%;
                right: 98%;
            }

            .items img {
                width: 100%;
                height: 70%;
            }

            input[type='submit'] {
                background-color: #AF9331;
                border: none;
                /* float: right; */
                top: -30px;
                position: relative;
                width: 70%;
                height: 30px;
                border-radius: 15px;
                color: white;
            }
        }

        @media screen and (min-width:1200px) {
            .right_des form select {
                border-radius: 2px;
                border: 1px solid black;
                background-color: white;
                width: 15%;
                height: 22px;
                margin-top: 10px;
            }
            .right_des {
                position: relative;
                width: 50%;
                left:1%;
                top: -19pc;
                float: right;
            }

            .items {
                width: 50%;
                position: relative;
                top: 7pc;
                border: 1px solid rgb(233, 212, 23);
                padding: 15px;
                left: 25%;
                margin-bottom:100px;
                height: 25pc;
                border-radius: 20px;
            }

            .items_img {
                position:relative;
                top:50px;
                left:5%;
                width: 43%;
                height: 360px;
            }

            .items img {
                width: 100%;
                height: 80%;
            }

            .right_des input[type='submit'] {
                background-color: #AF9331;
                border: none;
                /* float: right; */
                top: 40px;
                position: relative;
                width: 30%;
                height: 30px;
                left: -34%;
                border-radius: 15px;
                color: white;
            }

            .right_des h2,
            .right_des p,
            .des,
            select,
            option {
                color: black;
            }

            .right_des h2 {
                margin-top: 9px;
                margin-bottom: 9px;
            }

            select {
                position: relative;
                left: -66px;
                margin: 5px;
            }
            .right_des form {
                position: relative;
                left: -13px;
            }
            nav .icons {
                /* top: -32px; */
                position: relative;
            }

            nav input {
                color: black;
                position: relative;
                /* top: -32px; */
            }

            nav ul li {
                top: -12px;
                position: relative;
            }

            nav ul #mySelect {
                position: relative;
                top: -12px;
            }
        }
    </style>
</head>

<body>
   
    <div class="items">
        <div class="items_img">
            <img src="{% if product.image %}{{ product.image }}{% else %}
            {% static 'img/no_image.png' %}{% endif %}" alt="">
        </div>

        <div class="right_des">
            <h2>{{ product.name }}</h2>
          <span><strong style="color: black;">&#8358; {{ product.new_price|intcomma }}</strong></span>
            <del><sub style="color: black;">&#8358; {{ product.old_price }}</sub></del>
            <!-- <p><strong style="color: #AF9331;">&#8358;{{ product.new_price|intcomma }} </strong></p> -->
            <div class="des">{{ product.description }}</div>
            <form action="{% url 'cart:cart_add' product.id %}" method="post">
                {{ cart_product_form }}
                {% csrf_token %}
                <input style="cursor: pointer;" type="submit" name="" id="" value="Add to Cart">
            </form>
        </div>
    </div>


  
    <script src="https://kit.fontawesome.com/9da17deac8.js" crossorigin="anonymous"></script>
    <script src="{% static 'kobosh/swiper.js' %}"></script>
</body>

</html>
{% endblock %}